/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type AccountsListRequest = {
    cursor?: string | undefined;
    pageSize?: number | undefined;
    sort?: Array<string> | undefined;
    query?: string | undefined;
};

export type Cursor = {
    next?: string | undefined;
    data: Array<components.Account>;
};

/**
 * The request has succeeded.
 */
export type AccountsListResponseBody = {
    cursor: Cursor;
};

export type AccountsListResponse = {
    result: AccountsListResponseBody;
};

/** @internal */
export namespace AccountsListRequest$ {
    export const inboundSchema: z.ZodType<AccountsListRequest, z.ZodTypeDef, unknown> = z.object({
        cursor: z.string().optional(),
        pageSize: z.number().int().optional(),
        sort: z.array(z.string()).optional(),
        query: z.string().optional(),
    });

    export type Outbound = {
        cursor?: string | undefined;
        pageSize?: number | undefined;
        sort?: Array<string> | undefined;
        query?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AccountsListRequest> = z.object({
        cursor: z.string().optional(),
        pageSize: z.number().int().optional(),
        sort: z.array(z.string()).optional(),
        query: z.string().optional(),
    });
}

/** @internal */
export namespace Cursor$ {
    export const inboundSchema: z.ZodType<Cursor, z.ZodTypeDef, unknown> = z.object({
        next: z.string().optional(),
        data: z.array(components.Account$.inboundSchema),
    });

    export type Outbound = {
        next?: string | undefined;
        data: Array<components.Account$.Outbound>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Cursor> = z.object({
        next: z.string().optional(),
        data: z.array(components.Account$.outboundSchema),
    });
}

/** @internal */
export namespace AccountsListResponseBody$ {
    export const inboundSchema: z.ZodType<AccountsListResponseBody, z.ZodTypeDef, unknown> =
        z.object({
            cursor: z.lazy(() => Cursor$.inboundSchema),
        });

    export type Outbound = {
        cursor: Cursor$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AccountsListResponseBody> =
        z.object({
            cursor: z.lazy(() => Cursor$.outboundSchema),
        });
}

/** @internal */
export namespace AccountsListResponse$ {
    export const inboundSchema: z.ZodType<AccountsListResponse, z.ZodTypeDef, unknown> = z
        .object({
            Result: z.lazy(() => AccountsListResponseBody$.inboundSchema),
        })
        .transform((v) => {
            return remap$(v, {
                Result: "result",
            });
        });

    export type Outbound = {
        Result: AccountsListResponseBody$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AccountsListResponse> = z
        .object({
            result: z.lazy(() => AccountsListResponseBody$.outboundSchema),
        })
        .transform((v) => {
            return remap$(v, {
                result: "Result",
            });
        });
}
