/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type ConnectorsGetRequest = {
    connector: components.Connector;
    connectorId: string;
};

export type ConnectorsGetData =
    | components.WiseConfig
    | components.StripeConfig
    | components.GenericConfig
    | components.ModulrConfig
    | components.CurrencyCloudConfig
    | components.MangoPayConfig
    | components.MoneycorpConfig
    | components.AdyenConfig
    | components.DumypayConfig
    | components.AtlarConfig
    | components.BankingCircleConfig;

/**
 * The request has succeeded.
 */
export type ConnectorsGetResponseBody = {
    data:
        | components.WiseConfig
        | components.StripeConfig
        | components.GenericConfig
        | components.ModulrConfig
        | components.CurrencyCloudConfig
        | components.MangoPayConfig
        | components.MoneycorpConfig
        | components.AdyenConfig
        | components.DumypayConfig
        | components.AtlarConfig
        | components.BankingCircleConfig;
};

/** @internal */
export namespace ConnectorsGetRequest$ {
    export const inboundSchema: z.ZodType<ConnectorsGetRequest, z.ZodTypeDef, unknown> = z.object({
        connector: components.Connector$.inboundSchema,
        connectorId: z.string(),
    });

    export type Outbound = {
        connector: string;
        connectorId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ConnectorsGetRequest> = z.object(
        {
            connector: components.Connector$.outboundSchema,
            connectorId: z.string(),
        }
    );
}

/** @internal */
export namespace ConnectorsGetData$ {
    export const inboundSchema: z.ZodType<ConnectorsGetData, z.ZodTypeDef, unknown> = z.union([
        components.WiseConfig$.inboundSchema,
        components.StripeConfig$.inboundSchema,
        components.GenericConfig$.inboundSchema,
        components.ModulrConfig$.inboundSchema,
        components.CurrencyCloudConfig$.inboundSchema,
        components.MangoPayConfig$.inboundSchema,
        components.MoneycorpConfig$.inboundSchema,
        components.AdyenConfig$.inboundSchema,
        components.DumypayConfig$.inboundSchema,
        components.AtlarConfig$.inboundSchema,
        components.BankingCircleConfig$.inboundSchema,
    ]);

    export type Outbound =
        | components.WiseConfig$.Outbound
        | components.StripeConfig$.Outbound
        | components.GenericConfig$.Outbound
        | components.ModulrConfig$.Outbound
        | components.CurrencyCloudConfig$.Outbound
        | components.MangoPayConfig$.Outbound
        | components.MoneycorpConfig$.Outbound
        | components.AdyenConfig$.Outbound
        | components.DumypayConfig$.Outbound
        | components.AtlarConfig$.Outbound
        | components.BankingCircleConfig$.Outbound;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ConnectorsGetData> = z.union([
        components.WiseConfig$.outboundSchema,
        components.StripeConfig$.outboundSchema,
        components.GenericConfig$.outboundSchema,
        components.ModulrConfig$.outboundSchema,
        components.CurrencyCloudConfig$.outboundSchema,
        components.MangoPayConfig$.outboundSchema,
        components.MoneycorpConfig$.outboundSchema,
        components.AdyenConfig$.outboundSchema,
        components.DumypayConfig$.outboundSchema,
        components.AtlarConfig$.outboundSchema,
        components.BankingCircleConfig$.outboundSchema,
    ]);
}

/** @internal */
export namespace ConnectorsGetResponseBody$ {
    export const inboundSchema: z.ZodType<ConnectorsGetResponseBody, z.ZodTypeDef, unknown> =
        z.object({
            data: z.union([
                components.WiseConfig$.inboundSchema,
                components.StripeConfig$.inboundSchema,
                components.GenericConfig$.inboundSchema,
                components.ModulrConfig$.inboundSchema,
                components.CurrencyCloudConfig$.inboundSchema,
                components.MangoPayConfig$.inboundSchema,
                components.MoneycorpConfig$.inboundSchema,
                components.AdyenConfig$.inboundSchema,
                components.DumypayConfig$.inboundSchema,
                components.AtlarConfig$.inboundSchema,
                components.BankingCircleConfig$.inboundSchema,
            ]),
        });

    export type Outbound = {
        data:
            | components.WiseConfig$.Outbound
            | components.StripeConfig$.Outbound
            | components.GenericConfig$.Outbound
            | components.ModulrConfig$.Outbound
            | components.CurrencyCloudConfig$.Outbound
            | components.MangoPayConfig$.Outbound
            | components.MoneycorpConfig$.Outbound
            | components.AdyenConfig$.Outbound
            | components.DumypayConfig$.Outbound
            | components.AtlarConfig$.Outbound
            | components.BankingCircleConfig$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ConnectorsGetResponseBody> =
        z.object({
            data: z.union([
                components.WiseConfig$.outboundSchema,
                components.StripeConfig$.outboundSchema,
                components.GenericConfig$.outboundSchema,
                components.ModulrConfig$.outboundSchema,
                components.CurrencyCloudConfig$.outboundSchema,
                components.MangoPayConfig$.outboundSchema,
                components.MoneycorpConfig$.outboundSchema,
                components.AdyenConfig$.outboundSchema,
                components.DumypayConfig$.outboundSchema,
                components.AtlarConfig$.outboundSchema,
                components.BankingCircleConfig$.outboundSchema,
            ]),
        });
}
