/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type ConnectorsResetRequest = {
    connector: components.Connector;
    connectorId: string;
};

/** @internal */
export namespace ConnectorsResetRequest$ {
    export const inboundSchema: z.ZodType<ConnectorsResetRequest, z.ZodTypeDef, unknown> = z.object(
        {
            connector: components.Connector$.inboundSchema,
            connectorId: z.string(),
        }
    );

    export type Outbound = {
        connector: string;
        connectorId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ConnectorsResetRequest> =
        z.object({
            connector: components.Connector$.outboundSchema,
            connectorId: z.string(),
        });
}
