/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type WiseConfig = {
    name: string;
    /**
     * The frequency at which the connector will try to fetch new BalanceTransaction objects from Stripe API.
     */
    pollingPeriod?: string | undefined;
    apiKey: string;
};

/** @internal */
export namespace WiseConfig$ {
    export const inboundSchema: z.ZodType<WiseConfig, z.ZodTypeDef, unknown> = z.object({
        name: z.string(),
        pollingPeriod: z.string().default("120s"),
        apiKey: z.string(),
    });

    export type Outbound = {
        name: string;
        pollingPeriod: string;
        apiKey: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WiseConfig> = z.object({
        name: z.string(),
        pollingPeriod: z.string().default("120s"),
        apiKey: z.string(),
    });
}
