/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type LedgerPosting = {
    amount: number;
    asset: string;
    destination: string;
    source: string;
};

/** @internal */
export namespace LedgerPosting$ {
    export const inboundSchema: z.ZodType<LedgerPosting, z.ZodTypeDef, unknown> = z.object({
        amount: z.number().int(),
        asset: z.string(),
        destination: z.string(),
        source: z.string(),
    });

    export type Outbound = {
        amount: number;
        asset: string;
        destination: string;
        source: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, LedgerPosting> = z.object({
        amount: z.number().int(),
        asset: z.string(),
        destination: z.string(),
        source: z.string(),
    });
}
