/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { WalletCounterpart, WalletCounterpart$ } from "./walletcounterpart.js";
import * as z from "zod";

export type WalletsCreditWalletInputAmount = {
    asset: string;
    amount: number;
};

export type WalletsCreditWalletInput = {
    amount: WalletsCreditWalletInputAmount;
    metadata: { [k: string]: string };
    source: WalletCounterpart;
    reference?: string | undefined;
    balance?: string | undefined;
    tinestamp?: string | undefined;
};

/** @internal */
export namespace WalletsCreditWalletInputAmount$ {
    export const inboundSchema: z.ZodType<WalletsCreditWalletInputAmount, z.ZodTypeDef, unknown> =
        z.object({
            asset: z.string(),
            amount: z.number().int(),
        });

    export type Outbound = {
        asset: string;
        amount: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WalletsCreditWalletInputAmount> =
        z.object({
            asset: z.string(),
            amount: z.number().int(),
        });
}

/** @internal */
export namespace WalletsCreditWalletInput$ {
    export const inboundSchema: z.ZodType<WalletsCreditWalletInput, z.ZodTypeDef, unknown> =
        z.object({
            amount: z.lazy(() => WalletsCreditWalletInputAmount$.inboundSchema),
            metadata: z.record(z.string()),
            source: WalletCounterpart$.inboundSchema,
            reference: z.string().optional(),
            balance: z.string().optional(),
            tinestamp: z.string().optional(),
        });

    export type Outbound = {
        amount: WalletsCreditWalletInputAmount$.Outbound;
        metadata: { [k: string]: string };
        source: WalletCounterpart$.Outbound;
        reference?: string | undefined;
        balance?: string | undefined;
        tinestamp?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WalletsCreditWalletInput> =
        z.object({
            amount: z.lazy(() => WalletsCreditWalletInputAmount$.outboundSchema),
            metadata: z.record(z.string()),
            source: WalletCounterpart$.outboundSchema,
            reference: z.string().optional(),
            balance: z.string().optional(),
            tinestamp: z.string().optional(),
        });
}
