/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type InstancesAbortRequest = {
    id: string;
};

/** @internal */
export namespace InstancesAbortRequest$ {
    export const inboundSchema: z.ZodType<InstancesAbortRequest, z.ZodTypeDef, unknown> = z.object({
        id: z.string(),
    });

    export type Outbound = {
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, InstancesAbortRequest> =
        z.object({
            id: z.string(),
        });
}
