/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type WorkflowsRunRequest = {
    id: string;
    wait?: boolean | undefined;
    requestBody: { [k: string]: any };
};

/**
 * The request has succeeded.
 */
export type WorkflowsRunResponseBody = {
    data: components.WorkflowInstance;
};

/** @internal */
export namespace WorkflowsRunRequest$ {
    export const inboundSchema: z.ZodType<WorkflowsRunRequest, z.ZodTypeDef, unknown> = z
        .object({
            id: z.string(),
            wait: z.boolean().optional(),
            RequestBody: z.record(z.any()),
        })
        .transform((v) => {
            return remap$(v, {
                RequestBody: "requestBody",
            });
        });

    export type Outbound = {
        id: string;
        wait?: boolean | undefined;
        RequestBody: { [k: string]: any };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkflowsRunRequest> = z
        .object({
            id: z.string(),
            wait: z.boolean().optional(),
            requestBody: z.record(z.any()),
        })
        .transform((v) => {
            return remap$(v, {
                requestBody: "RequestBody",
            });
        });
}

/** @internal */
export namespace WorkflowsRunResponseBody$ {
    export const inboundSchema: z.ZodType<WorkflowsRunResponseBody, z.ZodTypeDef, unknown> =
        z.object({
            data: components.WorkflowInstance$.inboundSchema,
        });

    export type Outbound = {
        data: components.WorkflowInstance$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkflowsRunResponseBody> =
        z.object({
            data: components.WorkflowInstance$.outboundSchema,
        });
}
