/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type WorkflowsGetRequest = {
    id: string;
};

/**
 * The request has succeeded.
 */
export type WorkflowsGetResponseBody = {
    data: components.Workflow;
};

/** @internal */
export namespace WorkflowsGetRequest$ {
    export const inboundSchema: z.ZodType<WorkflowsGetRequest, z.ZodTypeDef, unknown> = z.object({
        id: z.string(),
    });

    export type Outbound = {
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkflowsGetRequest> = z.object({
        id: z.string(),
    });
}

/** @internal */
export namespace WorkflowsGetResponseBody$ {
    export const inboundSchema: z.ZodType<WorkflowsGetResponseBody, z.ZodTypeDef, unknown> =
        z.object({
            data: components.Workflow$.inboundSchema,
        });

    export type Outbound = {
        data: components.Workflow$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkflowsGetResponseBody> =
        z.object({
            data: components.Workflow$.outboundSchema,
        });
}
