/*
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const AddMetadataActionResponseResponseType = {
    AddMetadata: "ADD_METADATA",
} as const;
export type AddMetadataActionResponseResponseType = ClosedEnum<
    typeof AddMetadataActionResponseResponseType
>;

export type AddMetadataActionResponse = {
    responseType: AddMetadataActionResponseResponseType;
};

/** @internal */
export const AddMetadataActionResponseResponseType$inboundSchema: z.ZodNativeEnum<
    typeof AddMetadataActionResponseResponseType
> = z.nativeEnum(AddMetadataActionResponseResponseType);

/** @internal */
export const AddMetadataActionResponseResponseType$outboundSchema: z.ZodNativeEnum<
    typeof AddMetadataActionResponseResponseType
> = AddMetadataActionResponseResponseType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddMetadataActionResponseResponseType$ {
    /** @deprecated use `AddMetadataActionResponseResponseType$inboundSchema` instead. */
    export const inboundSchema = AddMetadataActionResponseResponseType$inboundSchema;
    /** @deprecated use `AddMetadataActionResponseResponseType$outboundSchema` instead. */
    export const outboundSchema = AddMetadataActionResponseResponseType$outboundSchema;
}

/** @internal */
export const AddMetadataActionResponse$inboundSchema: z.ZodType<
    AddMetadataActionResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    responseType: AddMetadataActionResponseResponseType$inboundSchema,
});

/** @internal */
export type AddMetadataActionResponse$Outbound = {
    responseType: string;
};

/** @internal */
export const AddMetadataActionResponse$outboundSchema: z.ZodType<
    AddMetadataActionResponse$Outbound,
    z.ZodTypeDef,
    AddMetadataActionResponse
> = z.object({
    responseType: AddMetadataActionResponseResponseType$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddMetadataActionResponse$ {
    /** @deprecated use `AddMetadataActionResponse$inboundSchema` instead. */
    export const inboundSchema = AddMetadataActionResponse$inboundSchema;
    /** @deprecated use `AddMetadataActionResponse$outboundSchema` instead. */
    export const outboundSchema = AddMetadataActionResponse$outboundSchema;
    /** @deprecated use `AddMetadataActionResponse$Outbound` instead. */
    export type Outbound = AddMetadataActionResponse$Outbound;
}
