/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const AddMetadataActionResponseResponseType = {
    AddMetadata: "ADD_METADATA",
} as const;
export type AddMetadataActionResponseResponseType = ClosedEnum<
    typeof AddMetadataActionResponseResponseType
>;

export type AddMetadataActionResponse = {
    responseType: AddMetadataActionResponseResponseType;
};

/** @internal */
export namespace AddMetadataActionResponseResponseType$ {
    export const inboundSchema: z.ZodNativeEnum<typeof AddMetadataActionResponseResponseType> =
        z.nativeEnum(AddMetadataActionResponseResponseType);
    export const outboundSchema: z.ZodNativeEnum<typeof AddMetadataActionResponseResponseType> =
        inboundSchema;
}

/** @internal */
export namespace AddMetadataActionResponse$ {
    export const inboundSchema: z.ZodType<AddMetadataActionResponse, z.ZodTypeDef, unknown> =
        z.object({
            responseType: AddMetadataActionResponseResponseType$.inboundSchema,
        });

    export type Outbound = {
        responseType: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddMetadataActionResponse> =
        z.object({
            responseType: AddMetadataActionResponseResponseType$.outboundSchema,
        });
}
