/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { AddMetadataAction, AddMetadataAction$ } from "./addmetadataaction.js";
import { CreateTransactionAction, CreateTransactionAction$ } from "./createtransactionaction.js";
import { DeleteMetadataAction, DeleteMetadataAction$ } from "./deletemetadataaction.js";
import { RevertTransactionAction, RevertTransactionAction$ } from "./reverttransactionaction.js";
import * as z from "zod";

export type BulkAction =
    | (CreateTransactionAction & { action: "CREATE_TRANSACTION" })
    | (AddMetadataAction & { action: "ADD_METADATA" })
    | (RevertTransactionAction & { action: "REVERT_TRANSACTION" })
    | (DeleteMetadataAction & { action: "DELETE_METADATA" });

/** @internal */
export namespace BulkAction$ {
    export const inboundSchema: z.ZodType<BulkAction, z.ZodTypeDef, unknown> = z.union([
        CreateTransactionAction$.inboundSchema.and(
            z
                .object({ action: z.literal("CREATE_TRANSACTION") })
                .transform((v) => ({ action: v.action }))
        ),
        AddMetadataAction$.inboundSchema.and(
            z.object({ action: z.literal("ADD_METADATA") }).transform((v) => ({ action: v.action }))
        ),
        RevertTransactionAction$.inboundSchema.and(
            z
                .object({ action: z.literal("REVERT_TRANSACTION") })
                .transform((v) => ({ action: v.action }))
        ),
        DeleteMetadataAction$.inboundSchema.and(
            z
                .object({ action: z.literal("DELETE_METADATA") })
                .transform((v) => ({ action: v.action }))
        ),
    ]);

    export type Outbound =
        | (CreateTransactionAction$.Outbound & { action: "CREATE_TRANSACTION" })
        | (AddMetadataAction$.Outbound & { action: "ADD_METADATA" })
        | (RevertTransactionAction$.Outbound & { action: "REVERT_TRANSACTION" })
        | (DeleteMetadataAction$.Outbound & { action: "DELETE_METADATA" });
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, BulkAction> = z.union([
        CreateTransactionAction$.outboundSchema.and(
            z
                .object({ action: z.literal("CREATE_TRANSACTION") })
                .transform((v) => ({ action: v.action }))
        ),
        AddMetadataAction$.outboundSchema.and(
            z.object({ action: z.literal("ADD_METADATA") }).transform((v) => ({ action: v.action }))
        ),
        RevertTransactionAction$.outboundSchema.and(
            z
                .object({ action: z.literal("REVERT_TRANSACTION") })
                .transform((v) => ({ action: v.action }))
        ),
        DeleteMetadataAction$.outboundSchema.and(
            z
                .object({ action: z.literal("DELETE_METADATA") })
                .transform((v) => ({ action: v.action }))
        ),
    ]);
}
