/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    AddMetadataActionResponse,
    AddMetadataActionResponse$,
} from "./addmetadataactionresponse.js";
import {
    CreateTransactionActionResponse,
    CreateTransactionActionResponse$,
} from "./createtransactionactionresponse.js";
import {
    DeleteMetadataActionResponse,
    DeleteMetadataActionResponse$,
} from "./deletemetadataactionresponse.js";
import {
    RevertTransactionActionResponse,
    RevertTransactionActionResponse$,
} from "./reverttransactionactionresponse.js";
import * as z from "zod";

export type BulkResponse =
    | (AddMetadataActionResponse & { responseType: "ADD_METADATA" })
    | (DeleteMetadataActionResponse & { responseType: "DELETE_METADATA" })
    | (CreateTransactionActionResponse & { responseType: "CREATE_TRANSACTION" })
    | (RevertTransactionActionResponse & { responseType: "REVERT_TRANSACTION" });

/** @internal */
export namespace BulkResponse$ {
    export const inboundSchema: z.ZodType<BulkResponse, z.ZodTypeDef, unknown> = z.union([
        AddMetadataActionResponse$.inboundSchema.and(
            z
                .object({ responseType: z.literal("ADD_METADATA") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
        DeleteMetadataActionResponse$.inboundSchema.and(
            z
                .object({ responseType: z.literal("DELETE_METADATA") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
        CreateTransactionActionResponse$.inboundSchema.and(
            z
                .object({ responseType: z.literal("CREATE_TRANSACTION") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
        RevertTransactionActionResponse$.inboundSchema.and(
            z
                .object({ responseType: z.literal("REVERT_TRANSACTION") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
    ]);

    export type Outbound =
        | (AddMetadataActionResponse$.Outbound & { responseType: "ADD_METADATA" })
        | (DeleteMetadataActionResponse$.Outbound & { responseType: "DELETE_METADATA" })
        | (CreateTransactionActionResponse$.Outbound & { responseType: "CREATE_TRANSACTION" })
        | (RevertTransactionActionResponse$.Outbound & { responseType: "REVERT_TRANSACTION" });
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, BulkResponse> = z.union([
        AddMetadataActionResponse$.outboundSchema.and(
            z
                .object({ responseType: z.literal("ADD_METADATA") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
        DeleteMetadataActionResponse$.outboundSchema.and(
            z
                .object({ responseType: z.literal("DELETE_METADATA") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
        CreateTransactionActionResponse$.outboundSchema.and(
            z
                .object({ responseType: z.literal("CREATE_TRANSACTION") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
        RevertTransactionActionResponse$.outboundSchema.and(
            z
                .object({ responseType: z.literal("REVERT_TRANSACTION") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
    ]);
}
