/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import {
    DeleteMetadataTarget,
    DeleteMetadataTarget$inboundSchema,
    DeleteMetadataTarget$Outbound,
    DeleteMetadataTarget$outboundSchema,
} from "./deletemetadatatarget.js";
import * as z from "zod";

export const DeleteMetadataActionAction = {
    DeleteMetadata: "DELETE_METADATA",
} as const;
export type DeleteMetadataActionAction = ClosedEnum<typeof DeleteMetadataActionAction>;

export type DeleteMetadataAction = {
    action: DeleteMetadataActionAction;
    ik?: string | undefined;
    data: DeleteMetadataTarget;
};

/** @internal */
export const DeleteMetadataActionAction$inboundSchema: z.ZodNativeEnum<
    typeof DeleteMetadataActionAction
> = z.nativeEnum(DeleteMetadataActionAction);

/** @internal */
export const DeleteMetadataActionAction$outboundSchema: z.ZodNativeEnum<
    typeof DeleteMetadataActionAction
> = DeleteMetadataActionAction$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteMetadataActionAction$ {
    /** @deprecated use `DeleteMetadataActionAction$inboundSchema` instead. */
    export const inboundSchema = DeleteMetadataActionAction$inboundSchema;
    /** @deprecated use `DeleteMetadataActionAction$outboundSchema` instead. */
    export const outboundSchema = DeleteMetadataActionAction$outboundSchema;
}

/** @internal */
export const DeleteMetadataAction$inboundSchema: z.ZodType<
    DeleteMetadataAction,
    z.ZodTypeDef,
    unknown
> = z.object({
    action: DeleteMetadataActionAction$inboundSchema,
    ik: z.string().optional(),
    data: DeleteMetadataTarget$inboundSchema,
});

/** @internal */
export type DeleteMetadataAction$Outbound = {
    action: string;
    ik?: string | undefined;
    data: DeleteMetadataTarget$Outbound;
};

/** @internal */
export const DeleteMetadataAction$outboundSchema: z.ZodType<
    DeleteMetadataAction$Outbound,
    z.ZodTypeDef,
    DeleteMetadataAction
> = z.object({
    action: DeleteMetadataActionAction$outboundSchema,
    ik: z.string().optional(),
    data: DeleteMetadataTarget$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteMetadataAction$ {
    /** @deprecated use `DeleteMetadataAction$inboundSchema` instead. */
    export const inboundSchema = DeleteMetadataAction$inboundSchema;
    /** @deprecated use `DeleteMetadataAction$outboundSchema` instead. */
    export const outboundSchema = DeleteMetadataAction$outboundSchema;
    /** @deprecated use `DeleteMetadataAction$Outbound` instead. */
    export type Outbound = DeleteMetadataAction$Outbound;
}
