/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const LogEntryType = {
    NewTransaction: "NEW_TRANSACTION",
    SetMetadata: "SET_METADATA",
    RevertTransaction: "REVERT_TRANSACTION",
} as const;
export type LogEntryType = ClosedEnum<typeof LogEntryType>;

/** @internal */
export namespace LogEntryType$ {
    export const inboundSchema: z.ZodNativeEnum<typeof LogEntryType> = z.nativeEnum(LogEntryType);
    export const outboundSchema: z.ZodNativeEnum<typeof LogEntryType> = inboundSchema;
}
