/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const MigrationState = {
    ToDo: "TO DO",
    Done: "DONE",
} as const;
export type MigrationState = ClosedEnum<typeof MigrationState>;

/** @internal */
export namespace MigrationState$ {
    export const inboundSchema: z.ZodNativeEnum<typeof MigrationState> =
        z.nativeEnum(MigrationState);
    export const outboundSchema: z.ZodNativeEnum<typeof MigrationState> = inboundSchema;
}
