/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Posting, Posting$ } from "./posting";
import * as z from "zod";

export type Transaction = {
    timestamp: Date;
    postings: Array<Posting>;
    reference?: string | undefined;
    metadata: { [k: string]: string };
    id: string;
    reverted: boolean;
};

/** @internal */
export namespace Transaction$ {
    export const inboundSchema: z.ZodType<Transaction, z.ZodTypeDef, unknown> = z.object({
        timestamp: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
        postings: z.array(Posting$.inboundSchema),
        reference: z.string().optional(),
        metadata: z.record(z.string()),
        id: z.string(),
        reverted: z.boolean(),
    });

    export type Outbound = {
        timestamp: string;
        postings: Array<Posting$.Outbound>;
        reference?: string | undefined;
        metadata: { [k: string]: string };
        id: string;
        reverted: boolean;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Transaction> = z.object({
        timestamp: z.date().transform((v) => v.toISOString()),
        postings: z.array(Posting$.outboundSchema),
        reference: z.string().optional(),
        metadata: z.record(z.string()),
        id: z.string(),
        reverted: z.boolean(),
    });
}
