/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    PaymentStatus,
    PaymentStatus$inboundSchema,
    PaymentStatus$outboundSchema,
} from "./paymentstatus.js";
import * as z from "zod";

export type TaskCurrencyCloud = {
    id: string;
    connectorID: string;
    createdAt: Date;
    updatedAt: Date;
    status: PaymentStatus;
    state: { [k: string]: any };
    error?: string | undefined;
    descriptor: string;
};

/** @internal */
export const TaskCurrencyCloud$inboundSchema: z.ZodType<TaskCurrencyCloud, z.ZodTypeDef, unknown> =
    z.object({
        id: z.string(),
        connectorID: z.string(),
        createdAt: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
        updatedAt: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
        status: PaymentStatus$inboundSchema,
        state: z.record(z.any()),
        error: z.string().optional(),
        descriptor: z.string(),
    });

/** @internal */
export type TaskCurrencyCloud$Outbound = {
    id: string;
    connectorID: string;
    createdAt: string;
    updatedAt: string;
    status: string;
    state: { [k: string]: any };
    error?: string | undefined;
    descriptor: string;
};

/** @internal */
export const TaskCurrencyCloud$outboundSchema: z.ZodType<
    TaskCurrencyCloud$Outbound,
    z.ZodTypeDef,
    TaskCurrencyCloud
> = z.object({
    id: z.string(),
    connectorID: z.string(),
    createdAt: z.date().transform((v) => v.toISOString()),
    updatedAt: z.date().transform((v) => v.toISOString()),
    status: PaymentStatus$outboundSchema,
    state: z.record(z.any()),
    error: z.string().optional(),
    descriptor: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskCurrencyCloud$ {
    /** @deprecated use `TaskCurrencyCloud$inboundSchema` instead. */
    export const inboundSchema = TaskCurrencyCloud$inboundSchema;
    /** @deprecated use `TaskCurrencyCloud$outboundSchema` instead. */
    export const outboundSchema = TaskCurrencyCloud$outboundSchema;
    /** @deprecated use `TaskCurrencyCloud$Outbound` instead. */
    export type Outbound = TaskCurrencyCloud$Outbound;
}
