/*
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

import {
    PaymentStatus,
    PaymentStatus$inboundSchema,
    PaymentStatus$outboundSchema,
} from "./paymentstatus.js";
import * as z from "zod";

export type TaskDummyPay = {
    id: string;
    connectorID: string;
    createdAt: Date;
    updatedAt: Date;
    status: PaymentStatus;
    state: { [k: string]: any };
    error?: string | undefined;
    descriptor: string;
};

/** @internal */
export const TaskDummyPay$inboundSchema: z.ZodType<TaskDummyPay, z.ZodTypeDef, unknown> = z.object({
    id: z.string(),
    connectorID: z.string(),
    createdAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    updatedAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    status: PaymentStatus$inboundSchema,
    state: z.record(z.any()),
    error: z.string().optional(),
    descriptor: z.string(),
});

/** @internal */
export type TaskDummyPay$Outbound = {
    id: string;
    connectorID: string;
    createdAt: string;
    updatedAt: string;
    status: string;
    state: { [k: string]: any };
    error?: string | undefined;
    descriptor: string;
};

/** @internal */
export const TaskDummyPay$outboundSchema: z.ZodType<
    TaskDummyPay$Outbound,
    z.ZodTypeDef,
    TaskDummyPay
> = z.object({
    id: z.string(),
    connectorID: z.string(),
    createdAt: z.date().transform((v) => v.toISOString()),
    updatedAt: z.date().transform((v) => v.toISOString()),
    status: PaymentStatus$outboundSchema,
    state: z.record(z.any()),
    error: z.string().optional(),
    descriptor: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskDummyPay$ {
    /** @deprecated use `TaskDummyPay$inboundSchema` instead. */
    export const inboundSchema = TaskDummyPay$inboundSchema;
    /** @deprecated use `TaskDummyPay$outboundSchema` instead. */
    export const outboundSchema = TaskDummyPay$outboundSchema;
    /** @deprecated use `TaskDummyPay$Outbound` instead. */
    export type Outbound = TaskDummyPay$Outbound;
}
