name: Publish
"on":
  push:
    branches:
      - main
    paths:
      - packages/client-ledger/RELEASES.md
      - packages/client-auth/RELEASES.md
      - packages/client-reconciliation/RELEASES.md
      - packages/client-wallets/RELEASES.md
      - packages/client-payments/RELEASES.md
      - packages/client-flows/RELEASES.md

jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      npm_token: ${{ secrets.NPM_TOKEN }}
